# fly.toml app configuration file generated for tasknow on 2023-07-02T19:35:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tasknow"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
